name: GitAct

on:
  push:
    branches:
      - main  # Jalankan setiap ada push di branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the target repository
    - name: Clone RepositoryName repository
      run: |
        git clone https://github.com/jokonotobot0/Menhera/LiyaaMD.zip

    # Step 2: Navigate into the LilyWa directory
    - name: Change directory to RepositoryName
      run: cd Menhera

    # Step 3: Unzip lilybot.zip file inside the LilyWa folder
    - name: Unzip File_Name.zip
      run: |
        sudo apt-get install unzip  # Install unzip tool if not already installed
        unzip Menhera/Liyaa%20MD%20(Free)%20v1.0.zip -d ./Menhera # Unzip File_Name.zip in the RepositoryName directory

    # Step 4: Install npm dependencies
    - name: Install npm dependencies
      run: |
        cd RepositoryName
        npm install

    # Step 5: Start the npm application
    - name: Start the application
      run: |
        cd RepositoryName
        npm start
